package_assets: on
embed_assets: off
compress_assets: off
gzip_assets: off
template_function: _.template

javascripts:
  tables:
    - bower_components/tabletop/src/tabletop.js
    - bower_components/jquery/jquery.js
    - bower_components/jquery.tablesorter/js/jquery.tablesorter.js
    - bower_components/underscore/underscore.js
    - js/jquery.tablesorter.multipagefilter.js
    - js/jquery.tablesorter.pager.js
    - js/table.js
    - templates/table.jst

stylesheets:
  tables:
    - bower_components/jquery.tablesorter/css/theme.default.css
    - bower_components/bootstrap/bootstrap/css/bootstrap.css
    - css/style.css